Traceback (most recent call last):
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/long/opt/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import libraries
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from time import sleep
import pandas as pd
import datefinder
import calendar
import os
import unittest
from random import randint
import PyPDF2
import glob
import pickle

driver_path = 'C:/Users/longy/OneDrive/Projects/AFRI/windows/chromedriver.exe'  #for windows
# driver_path = '/Users/Yanxu/OneDrive/Projects/AgPolicyCoding/chromedriver'
# driver = webdriver.Chrome(executable_path=DRIVER_PATH)

# Change the working directory
os.chdir('/Users/long/OneDrive/Projects/AFRI')
#os.chdir('C:/Users/longy/OneDrive/Projects/AFRI')
# os.chdir('/Volumes/GoogleDrive/Shared drives/UCSC-UMN AFRI project/Data/GA')
# Get the current working directory
cwd = os.getcwd()
# Print the current working directory
print("Current working directory: {0}".format(cwd))

chromeOptions = webdriver.ChromeOptions()
dnldpath = {"download.default_directory": "/Users/long/OneDrive/Projects/AFRI/data/ND/"}
chromeOptions.add_experimental_option('prefs', {
    "download.default_directory": dnldpath,  #Change default directory for downloads
    "download.prompt_for_download": False,  #To auto download the file
    "download.directory_upgrade": True,
    "plugins.always_open_pdf_externally": True,  #It will not show PDF directly in chrome
    "--enable-javascript": True
})
driver = webdriver.Chrome(executable_path=driver_path, options=chromeOptions)

print("Current working directory: {0}".format(cwd))

urls = []
sessionurls = []
driver.get("https://ndlegis.gov/session-laws/")
WebDriverWait(driver, 300).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, "div.view-content ul li a"))
)
sessions = driver.find_elements_by_css_selector('div.view-content ul li a')
for index, session in enumerate(sessions):
    print(index)
    print(session.text)
    sessionurl = session.get_attribute('href')
    sessionurls.append(sessionurl)

for sessionurl in sessionurls[:33]:
    driver.get(sessionurl)
    sleep(1)
    driver.find_element_by_link_text("Chapter Categories").click()
    try:
        chapters = driver.find_elements_by_css_selector('div.field-items ul li a')
        for chapter in chapters:
            url = chapter.get_attribute('href')
            urls.append(url)
    except:
        print(sessionurl)
print("urls are done")

acttxts = []
for idx, url in enumerate(urls):
    driver.get(url)
    sleep(1)
    path = "C:/Users/longy/OneDrive/Projects/AFRI/data/ND/"
    list_of_files = glob.glob(os.path.join(path, '*.pdf'))
    latest_file = max(list_of_files, key=os.path.getctime)
    print(latest_file)
    with open(os.path.join(os.getcwd(), latest_file), 'r') as f:  # open in readonly mode
        # creating a pdf File object of original pdf
        pdfFileObj = open(latest_file, 'rb')
        pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
        pagenumber = pdfReader.numPages
        acttxt = []
        pgtxts = []
        for p in range(pagenumber):
            pageObj = pdfReader.getPage(p)
            pgtxt = pageObj.extractText()
            pgtxts.append(pgtxt)
            acttxt = '\n'.join(pgtxts)
    acttxts.append(acttxt)
path = "C:/Users/longy/OneDrive/Projects/AFRI/data/ND/"
list_of_files = glob.glob(os.path.join(path, '*.pdf'))
#latest_file = max(list_of_files, key=os.path.getctime)
acttxts = []
for idx, file in enumerate(list_of_files):
    with open(os.path.join(os.getcwd(), file), 'r') as f:  # open in readonly mode
        # creating a pdf File object of original pdf
        pdfFileObj = open(file, 'rb')
        pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
        pagenumber = pdfReader.numPages
        acttxt = []
        pgtxts = []
        for p in range(pagenumber):
            pageObj = pdfReader.getPage(p)
            pgtxt = pageObj.extractText()
            pgtxts.append(pgtxt)
            acttxt = '  '.join(pgtxts)
    acttxts.append(acttxt)
datasource = pd.DataFrame({
    'Link to full text': urls,
    'Full text': acttxts
})

datasource = pd.DataFrame({
    'Full text': acttxts
})
datasource.to_excel('ND_Leginfo.xlsx')
datasource.to_csv('ND_Leginfo.csv')
datasource.to_pickle('ND_Leginfo.pkl')
datasource.to_json('ND_Leginfo.json')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/selenium/webdriver/common/service.py:72[0m, in [0;36mService.start[0;34m(self)[0m
[1;32m     71[0m     cmd[38;5;241m.[39mextend([38;5;28mself[39m[38;5;241m.[39mcommand_line_args())
[0;32m---> 72[0m     [38;5;28mself[39m[38;5;241m.[39mprocess [38;5;241m=[39m [43msubprocess[49m[38;5;241;43m.[39;49m[43mPopen[49m[43m([49m[43mcmd[49m[43m,[49m[43m [49m[43menv[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43menv[49m[43m,[49m
[1;32m     73[0m [43m                                    [49m[43mclose_fds[49m[38;5;241;43m=[39;49m[43mplatform[49m[38;5;241;43m.[39;49m[43msystem[49m[43m([49m[43m)[49m[43m [49m[38;5;241;43m!=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mWindows[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m     74[0m [43m                                    [49m[43mstdout[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mlog_file[49m[43m,[49m
[1;32m     75[0m [43m                                    [49m[43mstderr[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mlog_file[49m[43m,[49m
[1;32m     76[0m [43m                                    [49m[43mstdin[49m[38;5;241;43m=[39;49m[43mPIPE[49m[43m)[49m
[1;32m     77[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:

File [0;32m~/opt/anaconda3/envs/py39/lib/python3.9/subprocess.py:951[0m, in [0;36mPopen.__init__[0;34m(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)[0m
[1;32m    948[0m             [38;5;28mself[39m[38;5;241m.[39mstderr [38;5;241m=[39m io[38;5;241m.[39mTextIOWrapper([38;5;28mself[39m[38;5;241m.[39mstderr,
[1;32m    949[0m                     encoding[38;5;241m=[39mencoding, errors[38;5;241m=[39merrors)
[0;32m--> 951[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_execute_child[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mexecutable[49m[43m,[49m[43m [49m[43mpreexec_fn[49m[43m,[49m[43m [49m[43mclose_fds[49m[43m,[49m
[1;32m    952[0m [43m                        [49m[43mpass_fds[49m[43m,[49m[43m [49m[43mcwd[49m[43m,[49m[43m [49m[43menv[49m[43m,[49m
[1;32m    953[0m [43m                        [49m[43mstartupinfo[49m[43m,[49m[43m [49m[43mcreationflags[49m[43m,[49m[43m [49m[43mshell[49m[43m,[49m
[1;32m    954[0m [43m                        [49m[43mp2cread[49m[43m,[49m[43m [49m[43mp2cwrite[49m[43m,[49m
[1;32m    955[0m [43m                        [49m[43mc2pread[49m[43m,[49m[43m [49m[43mc2pwrite[49m[43m,[49m
[1;32m    956[0m [43m                        [49m[43merrread[49m[43m,[49m[43m [49m[43merrwrite[49m[43m,[49m
[1;32m    957[0m [43m                        [49m[43mrestore_signals[49m[43m,[49m
[1;32m    958[0m [43m                        [49m[43mgid[49m[43m,[49m[43m [49m[43mgids[49m[43m,[49m[43m [49m[43muid[49m[43m,[49m[43m [49m[43mumask[49m[43m,[49m
[1;32m    959[0m [43m                        [49m[43mstart_new_session[49m[43m)[49m
[1;32m    960[0m [38;5;28;01mexcept[39;00m:
[1;32m    961[0m     [38;5;66;03m# Cleanup if the child failed starting.[39;00m

File [0;32m~/opt/anaconda3/envs/py39/lib/python3.9/subprocess.py:1821[0m, in [0;36mPopen._execute_child[0;34m(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)[0m
[1;32m   1820[0m         err_msg [38;5;241m=[39m os[38;5;241m.[39mstrerror(errno_num)
[0;32m-> 1821[0m     [38;5;28;01mraise[39;00m child_exception_type(errno_num, err_msg, err_filename)
[1;32m   1822[0m [38;5;28;01mraise[39;00m child_exception_type(err_msg)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'C:/Users/longy/OneDrive/Projects/AFRI/windows/chromedriver.exe'

During handling of the above exception, another exception occurred:

[0;31mWebDriverException[0m                        Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 40>[0;34m()[0m
[1;32m     32[0m dnldpath [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mdownload.default_directory[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m/Users/long/OneDrive/Projects/AFRI/data/ND/[39m[38;5;124m"[39m}
[1;32m     33[0m chromeOptions[38;5;241m.[39madd_experimental_option([38;5;124m'[39m[38;5;124mprefs[39m[38;5;124m'[39m, {
[1;32m     34[0m     [38;5;124m"[39m[38;5;124mdownload.default_directory[39m[38;5;124m"[39m: dnldpath,  [38;5;66;03m#Change default directory for downloads[39;00m
[1;32m     35[0m     [38;5;124m"[39m[38;5;124mdownload.prompt_for_download[39m[38;5;124m"[39m: [38;5;28;01mFalse[39;00m,  [38;5;66;03m#To auto download the file[39;00m
[0;32m   (...)[0m
[1;32m     38[0m     [38;5;124m"[39m[38;5;124m--enable-javascript[39m[38;5;124m"[39m: [38;5;28;01mTrue[39;00m
[1;32m     39[0m })
[0;32m---> 40[0m driver [38;5;241m=[39m [43mwebdriver[49m[38;5;241;43m.[39;49m[43mChrome[49m[43m([49m[43mexecutable_path[49m[38;5;241;43m=[39;49m[43mdriver_path[49m[43m,[49m[43m [49m[43moptions[49m[38;5;241;43m=[39;49m[43mchromeOptions[49m[43m)[49m
[1;32m     42[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mCurrent working directory: [39m[38;5;132;01m{0}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(cwd))
[1;32m     44[0m urls [38;5;241m=[39m []

File [0;32m~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:73[0m, in [0;36mWebDriver.__init__[0;34m(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, keep_alive)[0m
[1;32m     66[0m         desired_capabilities[38;5;241m.[39mupdate(options[38;5;241m.[39mto_capabilities())
[1;32m     68[0m [38;5;28mself[39m[38;5;241m.[39mservice [38;5;241m=[39m Service(
[1;32m     69[0m     executable_path,
[1;32m     70[0m     port[38;5;241m=[39mport,
[1;32m     71[0m     service_args[38;5;241m=[39mservice_args,
[1;32m     72[0m     log_path[38;5;241m=[39mservice_log_path)
[0;32m---> 73[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mservice[49m[38;5;241;43m.[39;49m[43mstart[49m[43m([49m[43m)[49m
[1;32m     75[0m [38;5;28;01mtry[39;00m:
[1;32m     76[0m     RemoteWebDriver[38;5;241m.[39m[38;5;21m__init__[39m(
[1;32m     77[0m         [38;5;28mself[39m,
[1;32m     78[0m         command_executor[38;5;241m=[39mChromeRemoteConnection(
[1;32m     79[0m             remote_server_addr[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mservice[38;5;241m.[39mservice_url,
[1;32m     80[0m             keep_alive[38;5;241m=[39mkeep_alive),
[1;32m     81[0m         desired_capabilities[38;5;241m=[39mdesired_capabilities)

File [0;32m~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/selenium/webdriver/common/service.py:81[0m, in [0;36mService.start[0;34m(self)[0m
[1;32m     79[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err:
[1;32m     80[0m     [38;5;28;01mif[39;00m err[38;5;241m.[39merrno [38;5;241m==[39m errno[38;5;241m.[39mENOENT:
[0;32m---> 81[0m         [38;5;28;01mraise[39;00m WebDriverException(
[1;32m     82[0m             [38;5;124m"[39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m executable needs to be in PATH. [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m (
[1;32m     83[0m                 os[38;5;241m.[39mpath[38;5;241m.[39mbasename([38;5;28mself[39m[38;5;241m.[39mpath), [38;5;28mself[39m[38;5;241m.[39mstart_error_message)
[1;32m     84[0m         )
[1;32m     85[0m     [38;5;28;01melif[39;00m err[38;5;241m.[39merrno [38;5;241m==[39m errno[38;5;241m.[39mEACCES:
[1;32m     86[0m         [38;5;28;01mraise[39;00m WebDriverException(
[1;32m     87[0m             [38;5;124m"[39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m executable may have wrong permissions. [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m (
[1;32m     88[0m                 os[38;5;241m.[39mpath[38;5;241m.[39mbasename([38;5;28mself[39m[38;5;241m.[39mpath), [38;5;28mself[39m[38;5;241m.[39mstart_error_message)
[1;32m     89[0m         )

[0;31mWebDriverException[0m: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


